name: Update zigbee-frontend
on:
  repository_dispatch:
    types: update_frontend

jobs:
  update_frontend:
    runs-on: ubuntu-latest
    steps:
    - run: npm install zigbee2mqtt-frontend@${{ github.event.client_payload.version }} --save-exact
